language: rust
rust: nightly-2020-08-16

before_cache:
  - chmod -R a+r $HOME/.cargo

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

before_install:
  - df -h

jobs:
  include:
    - stage: "Build"
      name: Build (WASM and native)
      script:
        - RUST_TOOLCHAIN=nightly-2020-08-16 TARGET=build-client travis_wait 180 ./scripts/ci.sh
      deploy:
        - provider: script
          script: TARGET=default travis_wait 180 ./scripts/ci_docker.sh
          on:
            branch: master
        - provider: script
          script: TAG=$TRAVIS_TAG TARGET=release travis_wait 180 ./scripts/ci_docker.sh
          on:
            tags: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_script:
  - df -h

