language: rust

before_cache:
  - chmod -R a+r $HOME/.cargo

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

before_install:
  - df -h

jobs:
  include:
    - stage: "Build"
      name: Build (WASM and native)
      script:
        - RUST_TOOLCHAIN=nightly-2020-03-12 TARGET=build-client travis_wait 180 ./scripts/ci.sh

    - stage: "Release (Dockerhub/latest)"
      if: (NOT type IN (pull_request)) AND (branch = master) AND (TRAVIS_TAG == "")
      deploy:
        provider: script
        script: TARGET=default ./scripts/ci_docker.sh
        on:
          tags: false

    - stage: "Release (Dockerhub/vx.y.z)"
      if: (NOT type IN (pull_request)) AND (branch = master) AND (TRAVIS_TAG == "")
      deploy:
        provider: script
        script: TAG=$TRAVIS_TAG TARGET=release ./scripts/ci_docker.sh
        on:
          tags: true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_script:
  - df -h

