language: rust
rust: nightly-2020-08-16

before_cache:
  - chmod -R a+r $HOME/.cargo

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1
    - IMAGE_NAME="chainsafe/chainbridge-substrate-chain"

before_install:
  - df -h

jobs:
  include:
    - stage: "Build"
      name: Build (WASM and native)
      script:
        - travis_wait 180 docker build -t $IMAGE_NAME:latest .
      deploy:
        - provider: script
          script: TARGET=default ./scripts/ci_docker.sh
          on:
            branch: master
        - provider: script
          script: TAG=$TRAVIS_TAG TARGET=release ./scripts/ci_docker.sh
          on:
            tags: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_script:
  - df -h

